apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2019-12-23T20:42:15Z"
  generation: 4
  labels:
    app: my-rancher
  name: my-rancher
  namespace: local
  resourceVersion: "705344"
  selfLink: /apis/extensions/v1beta1/namespaces/local/deployments/my-rancher
  uid: b461efde-25c4-11ea-8883-025000000001
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: my-rancher
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: my-rancher
    spec:
      containers:
      - image: guilhermerenew/rancher:stable 
        imagePullPolicy: IfNotPresent
        name: server
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2019-12-23T20:42:16Z"
    lastUpdateTime: "2019-12-23T20:42:43Z"
    message: ReplicaSet "my-rancher-76c9bbbcff" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2019-12-23T21:18:28Z"
    lastUpdateTime: "2019-12-23T21:18:28Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 4
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
