apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2019-12-23T21:13:39Z"
  labels:
    app: my-rancher
  name: rancher
  namespace: local
  resourceVersion: "705065"
  selfLink: /api/v1/namespaces/local/services/rancher
  uid: 16ff8704-25c9-11ea-bf8a-025000000001
spec:
  clusterIP: 10.109.242.227
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 31431
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: my-rancher
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - hostname: localhost
