services:
  image: rancher/server:latest
  container_name: myroseno_rancher
  restart: unless-stopped
  volumes:
    - /tmp/user-rancher:/container/certs
  ports:
    - 8080:8080
  environment:
    SSL_CERT_DIR: /container/certs