  services:
    #rancher-server:
      image: rancher/rancher
      restart: unless-stopped
      container_name: myroseno
      volumes:
        - /var/lib/rancher
        - /var/log/auditlog
      ports:
        - "8443:443"